#!/usr/bin/env bash

# Parameterize
PYTHON_VERSION=3.6.4
BUILDDIR=/tmp/electrum-build
PACKAGE=Electrum
GIT_REPO=https://github.com/spesmilo/electrum

export PATH="~/Library/Python/3.6/bin:$PATH"
. $(dirname "$0")/base.sh

src_dir=$(dirname "$0")
cd $src_dir/../..
rm -rf ./dist

rm  -rf $BUILDDIR > /dev/null 2>&1
mkdir $BUILDDIR

export PYTHONHASHSEED=22
VERSION=`git describe --tags`

if [[ $(python3 -V 2>&1) == "Python $PYTHON_VERSION" ]] > /dev/null 2>&1; then
  info "Python $PYTHON_VERSION is already installed"
else
  curl -o $BUILDDIR/python-$PYTHON_VERSION.pkg https://www.python.org/ftp/python/$PYTHON_VERSION/python-$PYTHON_VERSION-macosx10.6.pkg
  info "Installing Python $PYTHON_VERSION"
  sudo installer -pkg $BUILDDIR/python-$PYTHON_VERSION.pkg -target /
fi

info "Installing pyinstaller"
python3 -m pip install git+https://github.com/ecdsa/pyinstaller@fix_2952 -I --user || fail "Could not install pyinstaller"

info "Using these versions for building $PACKAGE:"
sw_vers
python3 --version
echo -n "Pyinstaller "
pyinstaller --version


info "Downloading icons and locale..."
for repo in icons locale; do
  git clone $GIT_REPO-$repo $BUILDDIR/electrum-$repo
done

cp -R $BUILDDIR/electrum-locale/locale/ ./lib/locale/
cp    $BUILDDIR/electrum-icons/icons_rc.py ./gui/qt/


info "Downloading libusb..."
curl https://homebrew.bintray.com/bottles/libusb-1.0.22.el_capitan.bottle.tar.gz | \
tar xz --directory $BUILDDIR
cp $BUILDDIR/libusb/1.0.22/lib/libusb-1.0.dylib contrib/build-osx

info "Installing requirements..."
python3 -m pip install -Ir ./contrib/deterministic-build/requirements.txt --user && \
python3 -m pip install -Ir ./contrib/deterministic-build/requirements-binaries.txt --user || \
fail "Could not install requirements"

info "Installing hardware wallet requirements..."
python3 -m pip install -Ir ./contrib/deterministic-build/requirements-hw.txt --user || \
fail "Could not install hardware wallet requirements"

info "Installing prebuilt wheels for"
python3 -m pip uninstall -y pyblake2 hidapi
pushd $BUILDDIR
curl -O http://bauerj.eu/hidapi-0.7.99.post21-cp36-cp36m-macosx_10_6_intel.whl
curl -O http://bauerj.eu/pyblake2-1.1.1-cp36-cp36m-macosx_10_6_intel.whl
python3 -m pip install *.whl
popd

info "Building $PACKAGE..."
python3 setup.py install --user > /dev/null || fail "Could not build $PACKAGE"

info "Faking timestamps..."
for d in ~/Library/Python/ ~/.pyenv .; do
  pushd $d
  find . -exec touch -t '200101220000' {} +
  popd
done

info "Building binary"
pyinstaller --noconfirm --ascii --name $VERSION contrib/build-osx/osx.spec || fail "Could not build binary"

info "Creating .DMG"
hdiutil create -fs HFS+ -volname $PACKAGE -srcfolder dist/$PACKAGE.app dist/electrum-$VERSION.dmg || fail "Could not create .DMG"
